nome=input("Qual seu nome?")
dia=input("Dia do nascimento?")
mes=input("Mẽs de nascimento?")
ano=input("Ano de nascimento?")
msg1=("Você nasceu em")
msg2=("Correto?")
print(nome, msg1, dia, 'de',mes, 'de' ,ano, msg2)
